version: "3"
services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    networks:
      - mynetwork
    depends_on:
      - backend
networks:
  mynetwork:
