version: "3"
services: 
  nft-storage:
    build: .
    container_name: nft-storage
    volumes:
      - .:/
      - /node_modules
    ports:
      - "3000:3000"
    expose:
      - "3000"
    restart: always
    network:
      - "cactusNetwork"
    command: sh -c "tsc && node ./index.js"

networks:
  prod_app_net:
    external: true
